//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        public int IdArt { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public int Cantidad { get; set; }
        public string Rubro { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public short IdUnidadMedida { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
    
        public virtual UnidadesMedida UnidadesMedida { get; set; }
    }
}
